// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookDatatable: typeof import('./src/@core/components/book/BookDatatable.vue')['default']
    BookStatisticCard: typeof import('./src/@core/components/book/BookStatisticCard.vue')['default']
    BuyNow: typeof import('./src/@core/components/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    RoleVerticalNavLayout: typeof import('./src/@core/components/role/RoleVerticalNavLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticCard: typeof import('./src/@core/components/StatisticCard.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserDatatable: typeof import('./src/@core/components/user/UserDatatable.vue')['default']
    VerticalNavLayout: typeof import('./src/@core/components/role/VerticalNavLayout.vue')['default']
  }
}
